name: Build Todo App

on:
  push:
    branches: [ "main" ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    
    env:
      CONFIGURATION: development
    
    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - uses: pnpm/action-setup@v4
        with: 
          version: latest
          package_json_file: ./todo-app-frontend/package.json
        
      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
          cache-dependency-path: ./todo-app-frontend/package-lock.json
      
      - name: Build SPA frontend
      working-directory: ./todo-app-frontend
      run: |
        pnpm install --no-frozen-lockfile
        if [ ${{env.CONFIGURATION } == 'development'}]; then
          echo "Building development version"
        else
          echo "Building production version"
          pnpm run build
        fi
